### ISSUE TITLE
MsgServer.apk的二维码识别貌似出问题了

### ISSUE THREAD

**Issue by funrfun** [KrunkZhou/WebMessageServer#1]
你好，最后一步手机安装好apk，点击连接服务器扫描网页上二维码无反应，用微信扫码能扫出二维码信息，MsgServer.apk的二维码识别貌似出问题了，我换了多部手机安装apk均无法成功扫码，能解决这个问题吗，我愿意给小费

**Comment by KrunkZhou** [comment]
新年快乐！

二维码扫描需要手机支持GMS服务
已增加qr内容手动输入： https://github.com/KrunkZhou/WebMessageServer/commit/3d14457f9e9924e18173c0df8d3cccea17126cf8
